### ISSUE TITLE
Write the log filename somewhere on the page

### ISSUE THREAD

**Issue by MathiasVP** [asgerf/codeql-flamegraph-viewer#8]
I often compare two flame graph outputs, and when I do that I tend to forget which one is which. So as a workaround I set the title of one page to be "The old one" and the title of the other page to be "The new one".

Would it be possible to write something on the page when I load in a file that identifies which log file was used to generate the visualization?

**Comment by asgerf** [comment]
Good idea, I often run into the same issue myself. I've added the timestamp from the logfile to the header bar
<img width="638" alt="Screenshot 2021-04-14 at 11 38 56" src="https://user-images.githubusercontent.com/316427/114697603-04c82900-9d16-11eb-8a42-ccd016ace6a7.png">

We could show the name of the log file but in practice that just have the same information, and this also works when pasting the contents of the file.

(It will take a while for GitHub pages to refresh.)

**Comment by MathiasVP** [comment]
Looks like it's already refreshed. Thanks a lot!
